site_name: React Auth Kit
site_description: Authentication Library for React Js for Token Based Auth using Json Web Token(JWT)
site_author: Arkadip Bhattacharya
site_url: https://authkit.arkadip.me

repo_url: https://github.com/react-auth-kit/react-auth-kit
repo_name: react-auth-kit/react-auth-kit

copyright:  Copyright &copy; 2020 - 2021 React Auth Kit

theme:
  name: 'material'
  custom_dir: docs/docs_overrides/
  icon:
    repo: fontawesome/brands/github
  logo: img/logo.svg
  favicon: img/favicon.png
  palette:
    scheme: default
    primary: blue

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Integrate in your project: 'integration.md'
  - Sign In: 'signin.md'
  - Private Route: 'privateroute.md'
  - Sign Out: 'signout.md'
  - Auth User Data: 'authdata.md'
  - Auth Header: 'authheader.md'
  - Check Authentication: 'checkauth.md'
  - Refresh Token: 'refreshtoken.md'
  - Contributing: 'contributing.md'

extra:
  analytics:
    provider: google
    property: G-G1WZBFV5R2
  version:
    provider: mike

extra_javascript:
  - https://media.ethicalads.io/media/client/ethicalads.min.js

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
